-- ============================================================================
-- AUSTIN TRAFFIC HOTSPOT PREDICTION SCHEMA
-- Migration: 001_austin_schema.sql
-- Description: Creates tables for Austin traffic incident analysis and
--              hotspot prediction system
-- ============================================================================

-- 1. Austin Traffic Incidents (ingested from Austin Open Data API)
-- ============================================================================
-- Stores traffic incidents from https://data.austintexas.gov/resource/dx9v-zd7x.json
-- with computed fields for grid sector assignment and temporal analysis

CREATE TABLE IF NOT EXISTS public.austin_incidents (
    id SERIAL PRIMARY KEY,
    traffic_report_id VARCHAR(50) UNIQUE NOT NULL,
    published_date TIMESTAMP NOT NULL,
    issue_reported VARCHAR(255),
    location_type VARCHAR(100),
    address TEXT,
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    status VARCHAR(50),

    -- Computed fields for analysis
    grid_sector_id INTEGER,
    hour_of_day INTEGER,      -- 0-23
    day_of_week INTEGER,      -- 0=Monday, 6=Sunday

    created_at TIMESTAMP DEFAULT NOW(),

    -- Validate Austin coordinates (wider bounds to catch edge cases)
    CONSTRAINT valid_austin_coords CHECK (
        latitude BETWEEN 29.5 AND 31.0 AND
        longitude BETWEEN -98.5 AND -97.0
    )
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_austin_incidents_datetime
    ON public.austin_incidents(published_date);
CREATE INDEX IF NOT EXISTS idx_austin_incidents_sector
    ON public.austin_incidents(grid_sector_id);
CREATE INDEX IF NOT EXISTS idx_austin_incidents_hour_dow
    ON public.austin_incidents(hour_of_day, day_of_week);
CREATE INDEX IF NOT EXISTS idx_austin_incidents_issue
    ON public.austin_incidents(issue_reported);
CREATE INDEX IF NOT EXISTS idx_austin_incidents_status
    ON public.austin_incidents(status);


-- 2. Grid Sectors (100 sectors covering Austin metro area)
-- ============================================================================
-- Divides Austin into a 10x10 grid for hotspot analysis
-- Each sector is approximately 2.6 x 2.0 miles

CREATE TABLE IF NOT EXISTS public.austin_grid_sectors (
    id SERIAL PRIMARY KEY,
    sector_code VARCHAR(10) UNIQUE NOT NULL,  -- e.g., "A1", "B3", "J10"
    row_idx INTEGER NOT NULL,                  -- 0-9 (A-J)
    col_idx INTEGER NOT NULL,                  -- 0-9 (1-10)

    -- Bounding box coordinates
    north_lat DECIMAL(10, 7) NOT NULL,
    south_lat DECIMAL(10, 7) NOT NULL,
    east_lon DECIMAL(10, 7) NOT NULL,
    west_lon DECIMAL(10, 7) NOT NULL,

    -- Center point (for marker placement and distance calculations)
    center_lat DECIMAL(10, 7) NOT NULL,
    center_lon DECIMAL(10, 7) NOT NULL,

    -- Metadata
    area_sq_miles DECIMAL(8, 4),
    neighborhood_name VARCHAR(100),  -- e.g., "Downtown", "East Austin", "North Loop"

    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_grid_sectors_coords
    ON public.austin_grid_sectors(center_lat, center_lon);
CREATE INDEX IF NOT EXISTS idx_grid_sectors_code
    ON public.austin_grid_sectors(sector_code);


-- 3. Risk Scores (computed predictions per sector per hour)
-- ============================================================================
-- Stores hourly risk predictions generated by the Hotspot Agent
-- Used for visualization and deployment recommendations

CREATE TABLE IF NOT EXISTS public.austin_risk_scores (
    id SERIAL PRIMARY KEY,
    sector_id INTEGER REFERENCES public.austin_grid_sectors(id) ON DELETE CASCADE,

    -- Timestamps
    prediction_timestamp TIMESTAMP NOT NULL,  -- When prediction was computed
    target_hour TIMESTAMP NOT NULL,           -- Hour being predicted for

    -- Risk metrics
    risk_score DECIMAL(5, 4) NOT NULL,        -- 0.0000 to 1.0000
    risk_level VARCHAR(20),                   -- CRITICAL, HIGH, MEDIUM, LOW, MINIMAL
    confidence DECIMAL(5, 4),                 -- Confidence in prediction (0-1)

    -- Factor breakdown (for explainability)
    historical_factor DECIMAL(5, 4),          -- Base risk from historical patterns
    weather_factor DECIMAL(5, 4),             -- Weather multiplier applied
    time_factor DECIMAL(5, 4),                -- Time-of-day factor

    -- Detailed breakdown by incident type
    incident_type_breakdown JSONB,            -- {"CRASH": 0.3, "DISABLED VEHICLE": 0.2, ...}

    model_version VARCHAR(20) DEFAULT 'v1.0',
    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT valid_risk_score CHECK (risk_score >= 0 AND risk_score <= 1),
    CONSTRAINT valid_confidence CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX IF NOT EXISTS idx_risk_scores_target
    ON public.austin_risk_scores(target_hour);
CREATE INDEX IF NOT EXISTS idx_risk_scores_sector_hour
    ON public.austin_risk_scores(sector_id, target_hour);
CREATE INDEX IF NOT EXISTS idx_risk_scores_level
    ON public.austin_risk_scores(risk_level);
CREATE INDEX IF NOT EXISTS idx_risk_scores_timestamp
    ON public.austin_risk_scores(prediction_timestamp);


-- 4. Historical Patterns (pre-computed averages by sector/hour/day)
-- ============================================================================
-- Caches historical incident patterns for fast prediction queries
-- Updated periodically (e.g., daily) via compute_historical_patterns()

CREATE TABLE IF NOT EXISTS public.austin_historical_patterns (
    id SERIAL PRIMARY KEY,
    sector_id INTEGER REFERENCES public.austin_grid_sectors(id) ON DELETE CASCADE,

    -- Time slot definition
    day_of_week INTEGER NOT NULL,             -- 0=Monday, 6=Sunday
    hour_of_day INTEGER NOT NULL,             -- 0-23

    -- Aggregated metrics
    avg_incidents DECIMAL(8, 4),              -- Average incidents per this time slot
    incident_count INTEGER,                   -- Total incidents observed
    avg_severity DECIMAL(5, 4),               -- Average severity score (if available)
    incident_type_distribution JSONB,         -- {"CRASH": 45, "DISABLED VEHICLE": 30, ...}

    -- Sample info (for confidence calculation)
    sample_size INTEGER,                      -- Number of distinct days analyzed
    first_incident_date DATE,                 -- Earliest incident in sample
    last_incident_date DATE,                  -- Most recent incident in sample

    last_updated TIMESTAMP DEFAULT NOW(),

    CONSTRAINT valid_dow CHECK (day_of_week >= 0 AND day_of_week <= 6),
    CONSTRAINT valid_hour CHECK (hour_of_day >= 0 AND hour_of_day <= 23),
    UNIQUE(sector_id, day_of_week, hour_of_day)
);

CREATE INDEX IF NOT EXISTS idx_historical_patterns_time
    ON public.austin_historical_patterns(day_of_week, hour_of_day);
CREATE INDEX IF NOT EXISTS idx_historical_patterns_sector
    ON public.austin_historical_patterns(sector_id);


-- 5. Austin Weather Data (from NOAA)
-- ============================================================================
-- Stores weather observations and forecasts from NOAA Weather API
-- Used for weather-correlated risk predictions

CREATE TABLE IF NOT EXISTS public.austin_weather (
    id SERIAL PRIMARY KEY,
    datetime TIMESTAMP NOT NULL,

    -- Temperature
    temp DECIMAL(5, 2),                       -- Fahrenheit
    feels_like DECIMAL(5, 2),
    dew_point DECIMAL(5, 2),

    -- Precipitation
    humidity INTEGER,                         -- Percentage (0-100)
    precip DECIMAL(6, 4),                     -- Inches
    precip_probability INTEGER,               -- Percentage (0-100)
    precip_type VARCHAR(50),                  -- rain, snow, ice, sleet, etc.

    -- Wind
    wind_speed DECIMAL(5, 2),                 -- MPH
    wind_gust DECIMAL(5, 2),
    wind_direction INTEGER,                   -- Degrees (0-360)

    -- Visibility & conditions
    visibility DECIMAL(5, 2),                 -- Miles
    cloud_cover INTEGER,                      -- Percentage
    conditions VARCHAR(100),                  -- "Partly Cloudy", "Rain", "Thunderstorms", etc.

    -- Alerts and severe weather
    alerts JSONB,                             -- Active weather alerts from NOAA
    severe_risk INTEGER,                      -- 0-100 severe weather risk

    -- Source tracking
    forecast_or_actual VARCHAR(10) NOT NULL,  -- 'forecast' or 'actual'
    source VARCHAR(50) DEFAULT 'NOAA',

    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(datetime, forecast_or_actual)
);

CREATE INDEX IF NOT EXISTS idx_austin_weather_datetime
    ON public.austin_weather(datetime);
CREATE INDEX IF NOT EXISTS idx_austin_weather_type
    ON public.austin_weather(forecast_or_actual);
CREATE INDEX IF NOT EXISTS idx_austin_weather_conditions
    ON public.austin_weather(conditions);


-- 6. Deployment Recommendations (tow truck staging guidance)
-- ============================================================================
-- Stores generated deployment recommendations for emergency responders
-- Links to risk scores and provides actionable guidance

CREATE TABLE IF NOT EXISTS public.austin_deployment_recommendations (
    id SERIAL PRIMARY KEY,

    -- Timestamps
    recommendation_timestamp TIMESTAMP NOT NULL,
    target_period_start TIMESTAMP NOT NULL,
    target_period_end TIMESTAMP NOT NULL,

    -- Sector and priority
    sector_id INTEGER REFERENCES public.austin_grid_sectors(id) ON DELETE CASCADE,
    priority_rank INTEGER NOT NULL,           -- 1 = highest priority

    -- Recommendation details
    recommended_units INTEGER NOT NULL,       -- Number of tow trucks to stage
    risk_score DECIMAL(5, 4),
    risk_level VARCHAR(20),
    rationale TEXT,                           -- Human-readable explanation

    -- Context snapshot
    weather_conditions JSONB,                 -- Weather at time of recommendation
    nearby_incidents INTEGER,                 -- Recent incidents in sector
    historical_avg DECIMAL(8, 4),             -- Historical average for comparison

    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_deployment_target
    ON public.austin_deployment_recommendations(target_period_start);
CREATE INDEX IF NOT EXISTS idx_deployment_sector
    ON public.austin_deployment_recommendations(sector_id);
CREATE INDEX IF NOT EXISTS idx_deployment_active
    ON public.austin_deployment_recommendations(is_active);


-- 7. Prediction Accuracy Tracking (for model evaluation)
-- ============================================================================
-- Tracks prediction accuracy over time for model improvement

CREATE TABLE IF NOT EXISTS public.austin_prediction_accuracy (
    id SERIAL PRIMARY KEY,

    -- Reference to prediction
    risk_score_id INTEGER REFERENCES public.austin_risk_scores(id) ON DELETE CASCADE,
    sector_id INTEGER REFERENCES public.austin_grid_sectors(id) ON DELETE CASCADE,
    target_hour TIMESTAMP NOT NULL,

    -- Predicted vs actual
    predicted_risk DECIMAL(5, 4),
    predicted_level VARCHAR(20),
    actual_incidents INTEGER,                 -- Actual incidents that occurred

    -- Accuracy metrics
    was_accurate BOOLEAN,                     -- Did prediction match reality?
    error_magnitude DECIMAL(5, 4),            -- Difference between predicted and actual

    evaluated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_accuracy_hour
    ON public.austin_prediction_accuracy(target_hour);
CREATE INDEX IF NOT EXISTS idx_accuracy_sector
    ON public.austin_prediction_accuracy(sector_id);


-- ============================================================================
-- INITIALIZE GRID SECTORS (run once to populate 100 sectors)
-- ============================================================================
-- Creates a 10x10 grid covering Austin metro area
-- Sectors are labeled A1-J10 (row letter + column number)

DO $$
DECLARE
    row_idx INTEGER;
    col_idx INTEGER;
    sector_code VARCHAR(10);
    -- Austin bounding box
    north DECIMAL := 30.5167;
    south DECIMAL := 30.0833;
    east DECIMAL := -97.5833;
    west DECIMAL := -97.9167;
    -- Calculated steps
    lat_step DECIMAL;
    lon_step DECIMAL;
    -- Sector bounds
    s_north DECIMAL;
    s_south DECIMAL;
    s_east DECIMAL;
    s_west DECIMAL;
    s_center_lat DECIMAL;
    s_center_lon DECIMAL;
    s_area DECIMAL;
BEGIN
    lat_step := (north - south) / 10;
    lon_step := (east - west) / 10;

    -- Area calculation (approximate for Austin's latitude)
    -- 1 degree lat ≈ 69 miles, 1 degree lon ≈ 59 miles at 30°N
    s_area := (lat_step * 69) * (ABS(lon_step) * 59);

    FOR row_idx IN 0..9 LOOP
        FOR col_idx IN 0..9 LOOP
            -- Generate sector code: A1, A2, ... J10
            sector_code := CHR(65 + row_idx) || (col_idx + 1)::TEXT;

            -- Calculate sector bounds
            s_north := north - (row_idx * lat_step);
            s_south := s_north - lat_step;
            s_west := west + (col_idx * lon_step);
            s_east := s_west + lon_step;

            -- Calculate center point
            s_center_lat := (s_north + s_south) / 2;
            s_center_lon := (s_east + s_west) / 2;

            INSERT INTO public.austin_grid_sectors
                (sector_code, row_idx, col_idx,
                 north_lat, south_lat, east_lon, west_lon,
                 center_lat, center_lon, area_sq_miles)
            VALUES
                (sector_code, row_idx, col_idx,
                 s_north, s_south, s_east, s_west,
                 s_center_lat, s_center_lon, ROUND(s_area, 4))
            ON CONFLICT (sector_code) DO UPDATE SET
                north_lat = EXCLUDED.north_lat,
                south_lat = EXCLUDED.south_lat,
                east_lon = EXCLUDED.east_lon,
                west_lon = EXCLUDED.west_lon,
                center_lat = EXCLUDED.center_lat,
                center_lon = EXCLUDED.center_lon,
                area_sq_miles = EXCLUDED.area_sq_miles;
        END LOOP;
    END LOOP;

    RAISE NOTICE 'Created/updated 100 grid sectors (A1-J10)';
END $$;


-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function to get sector ID from coordinates
CREATE OR REPLACE FUNCTION get_sector_id(lat DECIMAL, lon DECIMAL)
RETURNS INTEGER AS $$
DECLARE
    north DECIMAL := 30.5167;
    south DECIMAL := 30.0833;
    east DECIMAL := -97.5833;
    west DECIMAL := -97.9167;
    rows INTEGER := 10;
    cols INTEGER := 10;
    lat_range DECIMAL;
    lon_range DECIMAL;
    row_idx INTEGER;
    col_idx INTEGER;
BEGIN
    -- Check bounds
    IF lat < south OR lat > north OR lon < west OR lon > east THEN
        RETURN NULL;
    END IF;

    lat_range := north - south;
    lon_range := east - west;

    -- Calculate row and column (0-indexed)
    row_idx := LEAST(GREATEST(FLOOR((north - lat) / lat_range * rows)::INTEGER, 0), rows - 1);
    col_idx := LEAST(GREATEST(FLOOR((lon - west) / lon_range * cols)::INTEGER, 0), cols - 1);

    -- Return 1-indexed sector ID
    RETURN row_idx * cols + col_idx + 1;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- Function to get sector code from ID
CREATE OR REPLACE FUNCTION get_sector_code(sector_id INTEGER)
RETURNS VARCHAR AS $$
BEGIN
    IF sector_id < 1 OR sector_id > 100 THEN
        RETURN NULL;
    END IF;

    RETURN CHR(65 + ((sector_id - 1) / 10)) || (((sector_id - 1) % 10) + 1)::TEXT;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- ============================================================================
-- VIEWS FOR COMMON QUERIES
-- ============================================================================

-- View: Current high-risk sectors (last hour predictions)
CREATE OR REPLACE VIEW public.austin_current_high_risk AS
SELECT
    rs.sector_id,
    gs.sector_code,
    gs.center_lat,
    gs.center_lon,
    rs.risk_score,
    rs.risk_level,
    rs.confidence,
    rs.weather_factor,
    rs.target_hour,
    rs.prediction_timestamp
FROM public.austin_risk_scores rs
JOIN public.austin_grid_sectors gs ON rs.sector_id = gs.id
WHERE rs.target_hour >= NOW() - INTERVAL '1 hour'
  AND rs.risk_level IN ('CRITICAL', 'HIGH')
ORDER BY rs.risk_score DESC;


-- View: Sector incident summary (last 7 days)
CREATE OR REPLACE VIEW public.austin_sector_summary AS
SELECT
    gs.id as sector_id,
    gs.sector_code,
    gs.center_lat,
    gs.center_lon,
    COUNT(ai.id) as incident_count,
    COUNT(DISTINCT DATE(ai.published_date)) as active_days,
    ARRAY_AGG(DISTINCT ai.issue_reported) as issue_types
FROM public.austin_grid_sectors gs
LEFT JOIN public.austin_incidents ai
    ON gs.id = ai.grid_sector_id
    AND ai.published_date >= NOW() - INTERVAL '7 days'
GROUP BY gs.id, gs.sector_code, gs.center_lat, gs.center_lon
ORDER BY incident_count DESC;


-- ============================================================================
-- GRANTS (adjust as needed for your user/role setup)
-- ============================================================================

-- Grant permissions to application user (if exists)
DO $$
BEGIN
    -- Uncomment and adjust if you have a specific app user
    -- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO traffix_app;
    -- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO traffix_app;
    NULL;
END $$;



-- ============================================================================
-- VERIFICATION QUERIES (run after migration to verify)
-- ============================================================================

-- Check grid sectors were created
-- SELECT COUNT(*) as sector_count FROM public.austin_grid_sectors;
-- Expected: 100

-- Sample sector data
-- SELECT sector_code, center_lat, center_lon, area_sq_miles
-- FROM public.austin_grid_sectors
-- ORDER BY sector_code LIMIT 10;

-- Test sector lookup function
-- SELECT get_sector_id(30.2672, -97.7431) as downtown_sector;
-- Expected: Sector near center of Austin (around E5 or E6)
